"""add message and create_match

Revision ID: 2687cddd95e5
Revises: 995d86ecbfc7
Create Date: 2020-08-03 13:57:55.200201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2687cddd95e5'
down_revision = '995d86ecbfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('create_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matcher', sa.Integer(), nullable=True),
    sa.Column('matchee', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['matchee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['matcher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1', sa.Integer(), nullable=True),
    sa.Column('user_2', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_1'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('match')
    op.drop_table('create_match')
    # ### end Alembic commands ###
