"""Add birthdate to user table

Revision ID: 7d585732ed37
Revises: b0fac0abc523
Create Date: 2020-09-06 15:41:28.908994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d585732ed37'
down_revision = 'b0fac0abc523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
