"""add zip

Revision ID: 995d86ecbfc7
Revises: 3df482c47e9a
Create Date: 2020-07-30 14:57:56.101197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995d86ecbfc7'
down_revision = '3df482c47e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('zip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'zip')
    # ### end Alembic commands ###
