"""update create match table

Revision ID: a3410a9d7c91
Revises: 2687cddd95e5
Create Date: 2020-08-13 10:25:01.794971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3410a9d7c91'
down_revision = '2687cddd95e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('create_match_id', sa.Integer(), nullable=True))
    op.drop_constraint('message_match_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'create_match', ['create_match_id'], ['id'])
    op.drop_column('message', 'match_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_match_id_fkey', 'message', 'match', ['match_id'], ['id'])
    op.drop_column('message', 'create_match_id')
    # ### end Alembic commands ###
