"""Add pass table

Revision ID: b0fac0abc523
Revises: b29f6ce15c71
Create Date: 2020-09-06 09:04:32.381020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fac0abc523'
down_revision = 'b29f6ce15c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passer', sa.Integer(), nullable=True),
    sa.Column('passee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['passee'], ['user.id'], ),
    sa.ForeignKeyConstraint(['passer'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pass')
    # ### end Alembic commands ###
